create an array of 10 zeros

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

create an array of 10 ones

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

create an array of 10 fives


In [15]:
np.full(10,5)


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

create an array of the integers ffrom 10 to 50 



In [16]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

create an array of  all the  even integers from 10 to 50

In [17]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [20]:
np.random.rand(1)

array([0.00369423])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
np.random.randn(25)


array([ 0.90755939, -0.12508626,  2.32671814, -0.44890797, -0.24536375,
        1.42710773,  0.15334721, -1.22967807,  0.49994953, -0.64568064,
       -1.2278867 , -1.52458609, -0.11944732, -0.50312446,  0.10773338,
        0.3356135 , -1.14272268,  1.4485199 , -0.43320143, -0.25807464,
        0.6556633 , -1.04889988,  0.28356969,  1.56215105, -0.24482564])

Create an array of 20 linearly spaced points between 0 and 1

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [25]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
mat[3][4]

20

In [29]:
mat[0:5,1].reshape(5,1)

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [30]:
mat[4]

array([21, 22, 23, 24, 25])

In [31]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])